# -*- coding: utf-8 -*-

# Auto-generated from tvsporedi.si
# Tuple format:
#     (channel_name, channel_id)

CHANNELS = [

    # ================== Splošni ==================
    ('3sat HD', '3sat'),
    ('Canale 5 HD', 'Canale 5 (DTT)'),
    ('Das Erste HD', 'Das Erste'),
    ('Duna TV HD', 'Duna TV'),
    ('France 2 HD', 'France 2'),
    ('Hayat HD', 'Hayat HD'),
    ('HTV 1 HD', 'HTV 1'),
    ('HTV 2 HD', 'HTV 2'),
    ('HTV 5 HD', 'HTV 5'),
    ('Italia 1 HD', 'Italia 1 (DTT)'),
    ('Kanal A HD', 'AKHD'),
    ('M1 HD', 'M1'),
    ('M2 HD', 'M2'),
    ('ORF 2 HD', 'ORF 2'),
    ('ORF eins HD', 'ORF eins'),
    ('Planet TV HD', 'PLHD'),
    ('POP TV HD', 'POHD'),
    ('RAI 1 HD', 'Rai 1'),
    ('RAI 2 HD', 'Rai 2'),
    ('RAI 3 HD', 'Rai 3'),
    ('RAI 4 HD', 'Rai 4'),
    ('RAI 5 HD', 'Rai 5'),
    ('Rete 4 HD', 'Rete 4 (DTT)'),
    ('RTS 1 HD', 'RTS1'),
    ('RTS 2 HD', 'RTS 2'),
    ('RTS Svet HD', 'RTS Sat'),
    ('TV 3 HD', 'TV3M'),
    ('TV 5 Monde Eu HD', 'TV5 Monde Europe'),
    ('TV Koper  HD', 'TVKP'),
    ('TV Maribor HD', 'TVMB'),
    ('TV Slovenija 1 HD', 'TVS1'),
    ('TV Slovenija 2 HD', 'TVS2'),
    ('TVCG 1 HD', 'TVCG1'),
    ('TVCG 2 HD', 'TVCG2'),
    ('ZDF HD', 'ZDF'),

    # ================== Filmski ==================
    ('AMC HD', 'AMC'),
    ('Astra HD', 'ASTA'),
    ('AXN HD', 'AXNS'),
    ('AXN Spin HD', 'AXNN'),
    ('BBC First HD', 'BBCF'),
    ('CineMax 2 HD', 'CMAX2'),
    ('CineMax HD', 'CMAX'),
    ('Cinestar Action HD', 'CAT'),
    ('Cinestar Comedy HD', 'CCF'),
    ('Cinestar Fantasy HD', 'CF'),
    ('Cinestar Premiere 1 HD', 'CP1'),
    ('Cinestar Premiere 2 HD', 'CP2'),
    ('Cinestar1 HD', 'CT1'),
    ('Cinestar2 HD', 'CT2'),
    ('Diva HD', 'DIVA'),
    ('Epic Drama HD', 'VEPI'),
    ('FilmBox+ Emotion', 'FBEM'),
    ('FilmBox+ Festival', 'FBFE'),
    ('FilmBox+ Hits', 'FBHI'),
    ('FilmBox+ Love&Crime', 'FBLC'),
    ('HBO 2 HD', 'HBO2'),
    ('HBO 3 HD', 'HBO3'),
    ('HBO HD', 'HBO'),
    ('Kino HD', 'KIHD'),
    ('KlasikTV HD', 'KlasikTV'),
    ('RAI Movie HD', 'Rai Movie'),
    ('RTL Adria HD', 'RTL Adria'),
    ('RTL Crime HD', 'RTL Crime'),
    ('RTL Passion HD', 'RTL Passion'),
    ('RTS Drama HD', 'RTSD'),
    ('Sci Fi HD', 'SAJF'),
    ('Star Crime HD', 'CRIM'),
    ('Star HD', 'STAR'),
    ('Star Life HD', 'LIFE'),
    ('Star Movies HD', 'MOVI'),
    ('Tele 5 HD', 'Tele 5'),
    ('Viasat Kino HD', 1000),

    # ================== Športni ==================
    ('Arena Sport 1 HD', 'ARS1'),
    ('Arena Sport 2 HD', 'ARS2'),
    ('Arena Sport 3 HD', 'ARS3'),
    ('Arena Sport 4 HD', 'ARS4'),
    ('Arena Sport Premium 1 HD', 'AS1P'),
    ('Eurosport 1 HD', 'ESHD'),
    ('Eurosport 2 HD', 'E2HD'),
    ('Eurosport 4K', 'ES4K'),
    ('Extreme Channel HD', 'EXTS'),
    ('ORF Sport+ HD', 'ORF Sport+'),
    ('RAI SportPiu HD', 'Rai SportPiu HD'),
    ('Sport1 HD', 'SPORT1'),
    ('SportKlub 1 HD', 'SK1HD'),
    ('SportKlub 2 HD', 'SK2HD'),
    ('SportKlub 3 HD', 'SK3HD'),
    ('SportKlub 4 HD', 'SK4HD'),
    ('SportKlub 4K', 'SK 4K'),
    ('SportKlub 5 HD', 'SK5HD'),
    ('SportKlub 6 HD', 'SK6HD'),
    ('SportKlub 7 HD', 'SK7HD'),
    ('SportKlub Fight HD', 'SKFIG'),
    ('SportKlub Golf HD', 'SKGHD'),
    ('Šport TV 1 HD', 'Sport TV 1'),
    ('Šport TV 2 HD', 'Sport TV 2'),
    ('Šport TV 3 HD', 'Sport TV 3'),

    # ================== Dokumentarni ==================
    ('24 Kitchen HD', '24KI'),
    ('Animal Planet HD', 'APHD'),
    ('ARTE HD', 'ARTE'),
    ('BBC Earth HD', 'BBCK'),
    ('Crime & Investigation HD', 'CINV'),
    ('Da Vinci HD', 'DVLR'),
    ('Discovery HD', 'DISC'),
    ('Discovery Science', 'SCIE'),
    ('Doku TV HD', 'DOKU TV'),
    ('DoxTV HD', 'DOXTV'),
    ('Food Network HD', 'FNHD'),
    ('HGTV HD', 'HGTV'),
    ('HIstory 2 Europe HD', 'History 2 HD'),
    ('History Channel HD', 'History HD'),
    ('ID HD', 'IDX'),
    ('Nautical Channel HD', 'YSAI'),
    ('NG Channel HD', 'HDNG'),
    ('NG Wild HD', 'NGWI'),
    ('RTS Trezor HD', 'RTS Trezor'),
    ('TLC HD', 'TLCB'),
    ('Travel Channel HD', 'TCHD'),
    ('Travel XP HD', 'TravelXP'),
    ('Viasat Explore HD', 'VEXP'),
    ('Viasat History HD', 'VIHI'),
    ('Viasat Nature HD', 'VNAT'),
    ('Viasat True Crime HD', 'VTC'),

    # ================== Otroški ==================
    ('Baby TV', 'BAFI'),
    ('Cartoon Network HD', 'CART'),
    ('Cartoonito HD', 'BOOM'),
    ('Disney Channel HD', 'DCHS'),
    ('Disney Junior HD', 'DIJU'),
    ('JimJam HD', 'JIMJ'),
    ('Minimax HD', 'MMAX'),
    ('Nick jr. HD', 'Nick jr'),
    ('Nickelodeon HD', 'Nickelodeon'),
    ('Nicktoons HD', 'Nicktoons'),
    ('Oto HD', 'OTHD'),
    ('RTL Kockica HD', 'RTL KOCKICA'),
    ('SuperRTL HD', 'Super RTL'),

    # ================== Informativni ==================
    ('BBC World HD', 'BBCW'),
    ('Bloomberg Adria HD', 'Bloomberg Adria'),
    ('CGTN HD', 'CGTN'),
    ('CNBC HD', 'CNBC'),
    ('CNN HD', 'CNN'),
    ('English Club HD', 'ENGL'),
    ('Euronews HD', 'Euronews'),
    ('France 24A HD', 'FRANCE 24 ANGLAIS'),
    ('France 24F HD', 'FRANCE 24 FRANCAIS'),
    ('GTV HD', 'GTV'),
    ('HTV 4 HD', 'HTV 4'),
    ('N1 HD BH', 'N1 HD (BH)/(BIH)'),
    ('Nova 24 TV HD', 'NO24'),
    ('ORF 3 HD', 'ORF 3'),
    ('RTS 3 HD', '3RTS'),
    ('RTS Maribor HD', 'RTS'),
    ('RTS Nauka HD', 'RTSN'),
    ('Sky News HD', 'Sky News'),
    ('TV Slovenija 3 HD', 'TVS3'),
    ('TVCG 3 HD', 'TVCG3'),
    ('TVMMC HD', 'TVMMC'),
    ('TVMNE HD', 'TVMNE'),
    ('Vaš kanal HD', 'VASK'),
    ('VOX HD', 'VOX'),
    ('VTV Velenje HD', 'VTV'),

    # ================== Zabavni ==================
    ('Aktual TV HD', 'AKTV'),
    ('Anixe HD', 'Anixe'),
    ('Arena TV HD', 'TV Arena'),
    ('Brio HD', 'BRHD'),
    ('E! HD', 'ENTE'),
    ('Fashion TV HD', 'Fashion TV'),
    ('GINX HD', 'GINX'),
    ('GOLD TV HD', 'GOLD'),
    ('Happy', 'HAPPY'),
    ('Hayat 2 HD', 'Hayat Plus'),
    ('HTV 3 HD', 'HTV 3'),
    ('Kabel Eins HD', 'Kabel Eins'),
    ('Lov i ribolov HD', 'LIRI'),
    ('MTV Europe HD', 'MTV Europe'),
    ('Net TV HD', 'NET'),
    ('Nova HD BH', 'Nova BH HD (BIH)'),
    ('Nova TV HD', 'NOVA TV'),
    ('OBN HD', 'OBN'),
    ('Pink Extra HD', 'Pink SI'),
    ('Pink Plus HD', 'Pink Plus'),
    ('Planet 2 HD', 'PLA2'),
    ('Planet Eva HD', 'PLEV'),
    ('Pro7 HD', 'ProSieben'),
    ('RTL 2 HR HD', 'RTL2'),
    ('RTL HD', 'RTL'),
    ('RTL II HD', 'RTL II'),
    ('RTL Living HD', 'RTL Living'),
    ('RTL TV HD', 'RTL TELEVIZIJA'),
    ('SAT.1 HD', 'SAT.1'),
    ('TV Veseljak HD', 'VESE'),

    # ================== Glasbeni ==================
    ('Adria HD', 'Adria'),
    ('DM Sat HD', 'DMSA'),
    ('iConcert HD', 'ICHD'),
    ('Mezzo HD', 'MEZZ'),
    ('Mezzo Live HD', 'MLHD'),
    ('My Zen HD', 'MZHD'),

    # ================== Ostalo ==================
    ('Hustler TV', 'HUST'),
    ('Hustler TV HD', 'HUHD'),
    ('Private TV HD', 'PRIV'),
]

# Example:
# SELECTED_GROUPS = ['Filmski']
# SELECTED_CHANNELS = [('HBO HD', 75)]
